### ISSUE TITLE
REST API docs for finalising a DataModel use incorrect body parameter names

### ISSUE THREAD

**Issue by spco** [MauroDataMapper/docs#70]
https://maurodatamapper.github.io/rest-api/resources/data-model/#finalise-a-data-model states that the body parameters for `dataModel/XXX/finalise` are `versionChange` and `version`. This is incorrect - they are `versionChangeType` and `version`.

**Comment by jamesrwelch** [comment]
Thanks for this, @spco - much appreciated.  We're working on a new version of the API docs here - https://documenter.getpostman.com/view/9840589/UVC8BkkA  (it helps if you switch "Environment" to "No Environment" to see all the parameters).  I'll make the change to the Docs here for now though :)
